## Scalar operations 

In [1]:
import dask.array as da

In [2]:
my_arr = da.random.randint(10, size=20, chunks=3)

In [3]:
my_arr.compute()

array([3, 0, 5, 5, 3, 2, 0, 9, 3, 7, 4, 6, 7, 8, 3, 0, 5, 8, 7, 8])

In [4]:
my_hundred_arr = my_arr + 100
my_hundred_arr.compute()

array([103, 100, 105, 105, 103, 102, 100, 109, 103, 107, 104, 106, 107,
       108, 103, 100, 105, 108, 107, 108])

In [5]:
(my_arr * (-1)).compute()

array([-3,  0, -5, -5, -3, -2,  0, -9, -3, -7, -4, -6, -7, -8, -3,  0, -5,
       -8, -7, -8])

## Reductions

In [7]:
dask_sum = my_arr.sum()
dask_sum

dask.array<sum-aggregate, shape=(), dtype=int64, chunksize=(), chunktype=numpy.ndarray>

In [8]:
my_arr.compute()

array([3, 0, 5, 5, 3, 2, 0, 9, 3, 7, 4, 6, 7, 8, 3, 0, 5, 8, 7, 8])

In [9]:
dask_sum.compute()

93

In [10]:
my_ones_arr = da.ones((10,10), chunks=2, dtype=int)

In [11]:
my_ones_arr.compute()

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [12]:
my_ones_arr.mean(axis=0).compute()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
my_custom_array = da.random.randint(10, size=(4,4), chunks=(1,4))

In [14]:
my_custom_array.compute()

array([[3, 6, 4, 7],
       [2, 5, 0, 0],
       [8, 6, 4, 5],
       [9, 6, 0, 9]])

In [15]:
my_custom_array.mean(axis=0).compute()

array([5.5 , 5.75, 2.  , 5.25])

In [16]:
my_custom_array.mean(axis=1).compute()

array([5.  , 1.75, 5.75, 6.  ])

## Slicing

In [17]:
my_custom_array[1:3, 2:4]

dask.array<getitem, shape=(2, 2), dtype=int64, chunksize=(1, 2), chunktype=numpy.ndarray>

In [18]:
my_custom_array[1:3, 2:4].compute()

array([[0, 0],
       [4, 5]])

## Broadcasting

In [19]:
my_custom_array.compute()

array([[3, 6, 4, 7],
       [2, 5, 0, 0],
       [8, 6, 4, 5],
       [9, 6, 0, 9]])

In [20]:
my_small_arr = da.ones(4, chunks=2)
my_small_arr.compute()

array([1., 1., 1., 1.])

In [21]:
brd_example1 = da.add(my_custom_array, my_small_arr)

In [22]:
# [[7, 1, 4, 4], + [[1, 1, 1, 1]
#  [1, 5, 5, 5],   [1, 1, 1, 1]
#  [9, 0, 2, 8],   [1, 1, 1, 1]
#  [1, 8, 8, 0]]   [1, 1, 1, 1]]
brd_example1.compute()

array([[ 4.,  7.,  5.,  8.],
       [ 3.,  6.,  1.,  1.],
       [ 9.,  7.,  5.,  6.],
       [10.,  7.,  1., 10.]])

In [23]:
ten_arr = da.full_like(my_small_arr, 10)

In [24]:
ten_arr.compute()

array([10., 10., 10., 10.])

In [25]:
brd_example2 = da.add(my_custom_array, ten_arr)

In [26]:
brd_example2.compute()

array([[13., 16., 14., 17.],
       [12., 15., 10., 10.],
       [18., 16., 14., 15.],
       [19., 16., 10., 19.]])

## Reshaping

In [27]:
my_custom_array.shape

(4, 4)

In [28]:
custom_arr_1d = my_custom_array.reshape(16)

In [29]:
custom_arr_1d

dask.array<reshape, shape=(16,), dtype=int64, chunksize=(4,), chunktype=numpy.ndarray>

In [30]:
custom_arr_1d.compute()

array([3, 6, 4, 7, 2, 5, 0, 0, 8, 6, 4, 5, 9, 6, 0, 9])

# Stacking

In [31]:
stacked_arr = da.stack([brd_example1, brd_example2])

In [32]:
stacked_arr.compute()

array([[[ 4.,  7.,  5.,  8.],
        [ 3.,  6.,  1.,  1.],
        [ 9.,  7.,  5.,  6.],
        [10.,  7.,  1., 10.]],

       [[13., 16., 14., 17.],
        [12., 15., 10., 10.],
        [18., 16., 14., 15.],
        [19., 16., 10., 19.]]])

In [33]:
another_stacked = da.stack([brd_example1, brd_example2], axis=1)

In [34]:
another_stacked.compute()

array([[[ 4.,  7.,  5.,  8.],
        [13., 16., 14., 17.]],

       [[ 3.,  6.,  1.,  1.],
        [12., 15., 10., 10.]],

       [[ 9.,  7.,  5.,  6.],
        [18., 16., 14., 15.]],

       [[10.,  7.,  1., 10.],
        [19., 16., 10., 19.]]])

# Concatenate

In [35]:
concate_arr = da.concatenate([brd_example1, brd_example2])

In [36]:
concate_arr.compute()

array([[ 4.,  7.,  5.,  8.],
       [ 3.,  6.,  1.,  1.],
       [ 9.,  7.,  5.,  6.],
       [10.,  7.,  1., 10.],
       [13., 16., 14., 17.],
       [12., 15., 10., 10.],
       [18., 16., 14., 15.],
       [19., 16., 10., 19.]])

In [37]:
another_concate_arr = da.concatenate([brd_example1, brd_example2],axis=1)

In [38]:
another_concate_arr.compute()

array([[ 4.,  7.,  5.,  8., 13., 16., 14., 17.],
       [ 3.,  6.,  1.,  1., 12., 15., 10., 10.],
       [ 9.,  7.,  5.,  6., 18., 16., 14., 15.],
       [10.,  7.,  1., 10., 19., 16., 10., 19.]])